plugins {
    id 'com.android.application'
}

android {
    namespace 'com.dev7sn.mafia'
    compileSdk 34

    defaultConfig {
        applicationId "com.dev7sn.mafia"
        minSdk 24
        targetSdk 34
        versionCode 5
        versionName "1.4"
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    applicationVariants.all { variant ->
        variant.outputs.all { output ->
            outputFileName = "Mafia.apk"
        }
    }
}
