plugins {
    id 'com.android.application'
}

android {
    namespace 'com.mafia.game'
    compileSdk 34

    defaultConfig {
        applicationId "com.mafia.game"
        minSdk 24
        targetSdk 34
        versionCode 2
        versionName "1.1"
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    applicationVariants.all { variant ->
        variant.outputs.all { output ->
            outputFileName = "Mafia.apk"
        }
    }
}
